<main>
        <div class="container-xxl">
            <div class="card text-center">
                <div class="card-body">
                  <h5 class="card-title">Formulário enviado com sucesso</h5>
                  <p class="card-text">Obrigado por seu contato! Já recebemos sua mensagem e responderemos o mais breve possível, fique de olho em seu email.</p>
                  <a href="#" class="btn btn-primary">Continue navegando</a>
                </div>
                <div class="card-footer text-body-secondary">
                  2 days ago
                </div>
              </div>
        </div>
    </main> 